/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { GhnDistrictDTO } from '../models';
// @ts-ignore
import { GhnProvinceDTO } from '../models';
// @ts-ignore
import { GhnWardDTO } from '../models';
/**
 * AddressApi - axios parameter creator
 * @export
 */
export const AddressApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get districts
         * @param {number} provinceId Mã tỉnh thành
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressControllerGetDistricts: async (provinceId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provinceId' is not null or undefined
            assertParamExists('addressControllerGetDistricts', 'provinceId', provinceId)
            const localVarPath = `/api/address/districts/{province_id}`
                .replace(`{${"province_id"}}`, encodeURIComponent(String(provinceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get provinces
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressControllerGetProvinces: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/address/provinces`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get wards
         * @param {number} districtId Mã quận huyện
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressControllerGetWards: async (districtId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'districtId' is not null or undefined
            assertParamExists('addressControllerGetWards', 'districtId', districtId)
            const localVarPath = `/api/address/wards/{district_id}`
                .replace(`{${"district_id"}}`, encodeURIComponent(String(districtId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AddressApi - functional programming interface
 * @export
 */
export const AddressApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AddressApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get districts
         * @param {number} provinceId Mã tỉnh thành
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addressControllerGetDistricts(provinceId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GhnDistrictDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addressControllerGetDistricts(provinceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AddressApi.addressControllerGetDistricts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get provinces
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addressControllerGetProvinces(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GhnProvinceDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addressControllerGetProvinces(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AddressApi.addressControllerGetProvinces']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get wards
         * @param {number} districtId Mã quận huyện
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addressControllerGetWards(districtId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GhnWardDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addressControllerGetWards(districtId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AddressApi.addressControllerGetWards']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AddressApi - factory interface
 * @export
 */
export const AddressApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AddressApiFp(configuration)
    return {
        /**
         * 
         * @summary Get districts
         * @param {AddressApiAddressControllerGetDistrictsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressControllerGetDistricts(requestParameters: AddressApiAddressControllerGetDistrictsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<GhnDistrictDTO>> {
            return localVarFp.addressControllerGetDistricts(requestParameters.provinceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get provinces
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressControllerGetProvinces(options?: RawAxiosRequestConfig): AxiosPromise<Array<GhnProvinceDTO>> {
            return localVarFp.addressControllerGetProvinces(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get wards
         * @param {AddressApiAddressControllerGetWardsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressControllerGetWards(requestParameters: AddressApiAddressControllerGetWardsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<GhnWardDTO>> {
            return localVarFp.addressControllerGetWards(requestParameters.districtId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addressControllerGetDistricts operation in AddressApi.
 * @export
 * @interface AddressApiAddressControllerGetDistrictsRequest
 */
export interface AddressApiAddressControllerGetDistrictsRequest {
    /**
     * Mã tỉnh thành
     * @type {number}
     * @memberof AddressApiAddressControllerGetDistricts
     */
    readonly provinceId: number
}

/**
 * Request parameters for addressControllerGetWards operation in AddressApi.
 * @export
 * @interface AddressApiAddressControllerGetWardsRequest
 */
export interface AddressApiAddressControllerGetWardsRequest {
    /**
     * Mã quận huyện
     * @type {number}
     * @memberof AddressApiAddressControllerGetWards
     */
    readonly districtId: number
}

/**
 * AddressApi - object-oriented interface
 * @export
 * @class AddressApi
 * @extends {BaseAPI}
 */
export class AddressApi extends BaseAPI {
    /**
     * 
     * @summary Get districts
     * @param {AddressApiAddressControllerGetDistrictsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressApi
     */
    public addressControllerGetDistricts(requestParameters: AddressApiAddressControllerGetDistrictsRequest, options?: RawAxiosRequestConfig) {
        return AddressApiFp(this.configuration).addressControllerGetDistricts(requestParameters.provinceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get provinces
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressApi
     */
    public addressControllerGetProvinces(options?: RawAxiosRequestConfig) {
        return AddressApiFp(this.configuration).addressControllerGetProvinces(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get wards
     * @param {AddressApiAddressControllerGetWardsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressApi
     */
    public addressControllerGetWards(requestParameters: AddressApiAddressControllerGetWardsRequest, options?: RawAxiosRequestConfig) {
        return AddressApiFp(this.configuration).addressControllerGetWards(requestParameters.districtId, options).then((request) => request(this.axios, this.basePath));
    }
}

