/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Actor
 */
export interface Actor {
    /**
     * 
     * @type {string}
     * @memberof Actor
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof Actor
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof Actor
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof Actor
     */
    'role': ActorRoleEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ActorRoleEnum {
    Manager = 'manager',
    Customer = 'customer',
    Sales = 'sales',
    Warehouse = 'warehouse'
}


