/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AttributeInProductSchemaDto
 */
export interface AttributeInProductSchemaDto {
    /**
     * 
     * @type {string}
     * @memberof AttributeInProductSchemaDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AttributeInProductSchemaDto
     */
    'k': string;
    /**
     * 
     * @type {string}
     * @memberof AttributeInProductSchemaDto
     */
    'v': string;
    /**
     * 
     * @type {string}
     * @memberof AttributeInProductSchemaDto
     */
    'u'?: string;
}

