/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserAddressSchemaDTO } from './user-address-schema-dto';

/**
 * 
 * @export
 * @interface AuthUpdateDto
 */
export interface AuthUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof AuthUpdateDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUpdateDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUpdateDto
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUpdateDto
     */
    'oldPassword'?: string;
    /**
     * 
     * @type {Array<UserAddressSchemaDTO>}
     * @memberof AuthUpdateDto
     */
    'address'?: Array<UserAddressSchemaDTO>;
    /**
     * 
     * @type {string}
     * @memberof AuthUpdateDto
     */
    'avatarImageId'?: string;
}

