/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthHttpExceptionDto
 */
export interface AuthHttpExceptionDto {
    /**
     * 
     * @type {number}
     * @memberof AuthHttpExceptionDto
     */
    'status': AuthHttpExceptionDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AuthHttpExceptionDto
     */
    'code': AuthHttpExceptionDtoCodeEnum;
    /**
     * 
     * @type {object}
     * @memberof AuthHttpExceptionDto
     */
    'errors'?: object;
}

/**
    * @export
    * @enum {string}
    */
export enum AuthHttpExceptionDtoStatusEnum {
    NUMBER_100 = 100,
    NUMBER_101 = 101,
    NUMBER_102 = 102,
    NUMBER_103 = 103,
    NUMBER_200 = 200,
    NUMBER_201 = 201,
    NUMBER_202 = 202,
    NUMBER_203 = 203,
    NUMBER_204 = 204,
    NUMBER_205 = 205,
    NUMBER_206 = 206,
    NUMBER_300 = 300,
    NUMBER_301 = 301,
    NUMBER_302 = 302,
    NUMBER_303 = 303,
    NUMBER_304 = 304,
    NUMBER_307 = 307,
    NUMBER_308 = 308,
    NUMBER_400 = 400,
    NUMBER_401 = 401,
    NUMBER_402 = 402,
    NUMBER_403 = 403,
    NUMBER_404 = 404,
    NUMBER_405 = 405,
    NUMBER_406 = 406,
    NUMBER_407 = 407,
    NUMBER_408 = 408,
    NUMBER_409 = 409,
    NUMBER_410 = 410,
    NUMBER_411 = 411,
    NUMBER_412 = 412,
    NUMBER_413 = 413,
    NUMBER_414 = 414,
    NUMBER_415 = 415,
    NUMBER_416 = 416,
    NUMBER_417 = 417,
    NUMBER_418 = 418,
    NUMBER_421 = 421,
    NUMBER_422 = 422,
    NUMBER_424 = 424,
    NUMBER_428 = 428,
    NUMBER_429 = 429,
    NUMBER_500 = 500,
    NUMBER_501 = 501,
    NUMBER_502 = 502,
    NUMBER_503 = 503,
    NUMBER_504 = 504,
    NUMBER_505 = 505
}
/**
    * @export
    * @enum {string}
    */
export enum AuthHttpExceptionDtoCodeEnum {
    EmailAlreadyExists = 'auth.emailAlreadyExists',
    UserNotFound = 'auth.userNotFound',
    EmailAlreadyConfirmed = 'auth.emailAlreadyConfirmed',
    InvalidHash = 'auth.invalidHash',
    WrongProvider = 'auth.wrongProvider',
    WrongEmailOrPassword = 'auth.wrongEmailOrPassword',
    MissingOldPassword = 'auth.missingOldPassword',
    InvalidAddress = 'auth.invalidAddress',
    InvalidImageId = 'auth.invalidImageId',
    AccessTokenInvalid = 'auth.accessTokenInvalid',
    AccessTokenRevoked = 'auth.accessTokenRevoked',
    RefreshTokenInvalid = 'auth.refreshTokenInvalid',
    RefreshTokenRevoked = 'auth.refreshTokenRevoked'
}


