/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthSignupDto
 */
export interface AuthSignupDto {
    /**
     * The user\'s email address.
     * @type {string}
     * @memberof AuthSignupDto
     */
    'email': string;
    /**
     * The user\'s password.
     * @type {string}
     * @memberof AuthSignupDto
     */
    'password': string;
    /**
     * The user\'s first name.
     * @type {string}
     * @memberof AuthSignupDto
     */
    'firstName': string;
    /**
     * The user\'s last name.
     * @type {string}
     * @memberof AuthSignupDto
     */
    'lastName': string;
}

