/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlockActivityLog
 */
export interface BlockActivityLog {
    /**
     * 
     * @type {string}
     * @memberof BlockActivityLog
     */
    'action': BlockActivityLogActionEnum;
    /**
     * 
     * @type {string}
     * @memberof BlockActivityLog
     */
    'actionAt': string;
    /**
     * 
     * @type {string}
     * @memberof BlockActivityLog
     */
    'actionBy': string;
    /**
     * 
     * @type {string}
     * @memberof BlockActivityLog
     */
    'reason': string;
    /**
     * 
     * @type {string}
     * @memberof BlockActivityLog
     */
    'note': string;
}

/**
    * @export
    * @enum {string}
    */
export enum BlockActivityLogActionEnum {
    Block = 'block',
    Unblock = 'unblock'
}


