/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProductCartSchema } from './product-cart-schema';

/**
 * 
 * @export
 * @interface Cart
 */
export interface Cart {
    /**
     * 
     * @type {string}
     * @memberof Cart
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof Cart
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Cart
     */
    'updatedAt': string;
    /**
     * User ID
     * @type {string}
     * @memberof Cart
     */
    'userId': string;
    /**
     * List of products in cart
     * @type {Array<ProductCartSchema>}
     * @memberof Cart
     */
    'products'?: Array<ProductCartSchema>;
}

