/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateTagDto
 */
export interface CreateTagDto {
    /**
     * Tên nhãn
     * @type {string}
     * @memberof CreateTagDto
     */
    'name': string;
    /**
     * Mô tả
     * @type {string}
     * @memberof CreateTagDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof CreateTagDto
     */
    'status'?: CreateTagDtoStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateTagDtoStatusEnum {
    Active = 'active',
    Deleted = 'deleted'
}


