/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateAttributeDto
 */
export interface CreateAttributeDto {
    /**
     * Attribute label. Label must only contain lowercase letters and optional underscores
     * @type {string}
     * @memberof CreateAttributeDto
     */
    'label': string;
    /**
     * Attribute name, can be in any language
     * @type {string}
     * @memberof CreateAttributeDto
     */
    'name': string;
    /**
     * Unit abbreviation for this attribute
     * @type {string}
     * @memberof CreateAttributeDto
     */
    'unit'?: string;
    /**
     * Attribute description
     * @type {string}
     * @memberof CreateAttributeDto
     */
    'description'?: string;
}

