/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateBrandDto
 */
export interface CreateBrandDto {
    /**
     * 
     * @type {string}
     * @memberof CreateBrandDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBrandDto
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBrandDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBrandDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBrandDto
     */
    'status'?: CreateBrandDtoStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateBrandDtoStatusEnum {
    Active = 'active',
    Inactive = 'inactive',
    Deleted = 'deleted'
}


