/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * The user\'s email address.
     * @type {string}
     * @memberof CreateUserDto
     */
    'email': string;
    /**
     * The user\'s password.
     * @type {string}
     * @memberof CreateUserDto
     */
    'password': string;
    /**
     * The user\'s first name.
     * @type {string}
     * @memberof CreateUserDto
     */
    'firstName': string;
    /**
     * The user\'s last name.
     * @type {string}
     * @memberof CreateUserDto
     */
    'lastName': string;
    /**
     * The user\'s role.
     * @type {string}
     * @memberof CreateUserDto
     */
    'role': CreateUserDtoRoleEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateUserDtoRoleEnum {
    Sales = 'sales',
    Warehouse = 'warehouse'
}


