/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttributeInProductSchemaDto } from './attribute-in-product-schema-dto';
// May contain unused imports in some cases
// @ts-ignore
import { SPUModelSchemaDto } from './spumodel-schema-dto';

/**
 * 
 * @export
 * @interface CreateSpuDto
 */
export interface CreateSpuDto {
    /**
     * Brand id
     * @type {string}
     * @memberof CreateSpuDto
     */
    'brandId': string;
    /**
     * Spu name
     * @type {string}
     * @memberof CreateSpuDto
     */
    'name': string;
    /**
     * Spu description
     * @type {string}
     * @memberof CreateSpuDto
     */
    'description'?: string;
    /**
     * Common attributes
     * @type {Array<AttributeInProductSchemaDto>}
     * @memberof CreateSpuDto
     */
    'commonAttributes'?: Array<AttributeInProductSchemaDto>;
    /**
     * Models
     * @type {Array<SPUModelSchemaDto>}
     * @memberof CreateSpuDto
     */
    'models'?: Array<SPUModelSchemaDto>;
    /**
     * Spu status
     * @type {string}
     * @memberof CreateSpuDto
     */
    'status'?: CreateSpuDtoStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateSpuDtoStatusEnum {
    Available = 'available',
    Deleted = 'deleted'
}


