/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilterBrandsDto
 */
export interface FilterBrandsDto {
    /**
     * Search by keyword
     * @type {string}
     * @memberof FilterBrandsDto
     */
    'keyword'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterBrandsDto
     */
    'status'?: Array<FilterBrandsDtoStatusEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum FilterBrandsDtoStatusEnum {
    Active = 'active',
    Inactive = 'inactive',
    Deleted = 'deleted'
}


