/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilterUserDto
 */
export interface FilterUserDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterUserDto
     */
    'roles'?: Array<FilterUserDtoRolesEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum FilterUserDtoRolesEnum {
    Manager = 'manager',
    Customer = 'customer',
    Sales = 'sales',
    Warehouse = 'warehouse'
}


