/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilterSpuDto
 */
export interface FilterSpuDto {
    /**
     * Search by keyword
     * @type {string}
     * @memberof FilterSpuDto
     */
    'keyword'?: string;
    /**
     * List of status of SPU
     * @type {Array<string>}
     * @memberof FilterSpuDto
     */
    'status'?: Array<FilterSpuDtoStatusEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum FilterSpuDtoStatusEnum {
    Available = 'available',
    Deleted = 'deleted'
}


