/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilterSkuDto
 */
export interface FilterSkuDto {
    /**
     * Search by keyword
     * @type {string}
     * @memberof FilterSkuDto
     */
    'keyword'?: string;
    /**
     * List of status of SKU
     * @type {Array<string>}
     * @memberof FilterSkuDto
     */
    'status'?: Array<FilterSkuDtoStatusEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum FilterSkuDtoStatusEnum {
    Selling = 'selling',
    Deleted = 'deleted',
    NewlyReleased = 'newly-released'
}


