/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilterAttributeDto
 */
export interface FilterAttributeDto {
    /**
     * 
     * @type {string}
     * @memberof FilterAttributeDto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof FilterAttributeDto
     */
    'updatedAt'?: string;
    /**
     * Attribute label, unique
     * @type {string}
     * @memberof FilterAttributeDto
     */
    'label'?: string;
    /**
     * Attribute name, can be translated
     * @type {string}
     * @memberof FilterAttributeDto
     */
    'name'?: string;
    /**
     * Attribute unit
     * @type {string}
     * @memberof FilterAttributeDto
     */
    'unit'?: string;
    /**
     * 
     * @type {string}
     * @memberof FilterAttributeDto
     */
    'description'?: string;
    /**
     * Search by keyword
     * @type {string}
     * @memberof FilterAttributeDto
     */
    'keyword'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterAttributeDto
     */
    'status'?: Array<FilterAttributeDtoStatusEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum FilterAttributeDtoStatusEnum {
    Available = 'available',
    Deleted = 'deleted'
}


