/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GhnWardDTO
 */
export interface GhnWardDTO {
    /**
     * Mã quận huyện
     * @type {number}
     * @memberof GhnWardDTO
     */
    'districtId': number;
    /**
     * Mã phường xã
     * @type {string}
     * @memberof GhnWardDTO
     */
    'wardCode': string;
    /**
     * Tên phường xã
     * @type {string}
     * @memberof GhnWardDTO
     */
    'wardName': string;
    /**
     * Tên phường xã mở rộng
     * @type {Array<string>}
     * @memberof GhnWardDTO
     */
    'nameExtension': Array<string>;
    /**
     * Loại hỗ trợ
     * @type {number}
     * @memberof GhnWardDTO
     */
    'supportType': GhnWardDTOSupportTypeEnum;
    /**
     * Có thể cập nhật COD
     * @type {boolean}
     * @memberof GhnWardDTO
     */
    'canUpdateCod': boolean;
    /**
     * Trạng thái
     * @type {number}
     * @memberof GhnWardDTO
     */
    'status': GhnWardDTOStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum GhnWardDTOSupportTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
    * @export
    * @enum {string}
    */
export enum GhnWardDTOStatusEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


