/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GhnDistrictDTO
 */
export interface GhnDistrictDTO {
    /**
     * Mã tỉnh thành
     * @type {number}
     * @memberof GhnDistrictDTO
     */
    'provinceId': number;
    /**
     * Mã quận huyện
     * @type {number}
     * @memberof GhnDistrictDTO
     */
    'districtId': number;
    /**
     * Tên quận huyện
     * @type {string}
     * @memberof GhnDistrictDTO
     */
    'districtName': string;
    /**
     * Loại hỗ trợ
     * @type {number}
     * @memberof GhnDistrictDTO
     */
    'supportType': GhnDistrictDTOSupportTypeEnum;
    /**
     * Tên quận huyện mở rộng
     * @type {Array<string>}
     * @memberof GhnDistrictDTO
     */
    'nameExtension': Array<string>;
    /**
     * Có thể cập nhật COD
     * @type {boolean}
     * @memberof GhnDistrictDTO
     */
    'canUpdateCod': boolean;
    /**
     * Trạng thái
     * @type {number}
     * @memberof GhnDistrictDTO
     */
    'status': GhnDistrictDTOStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum GhnDistrictDTOSupportTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
    * @export
    * @enum {string}
    */
export enum GhnDistrictDTOStatusEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


