/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Actor } from './actor';

/**
 * 
 * @export
 * @interface OrderLogSchema
 */
export interface OrderLogSchema {
    /**
     * 
     * @type {Actor}
     * @memberof OrderLogSchema
     */
    'actor': Actor;
    /**
     * 
     * @type {string}
     * @memberof OrderLogSchema
     */
    'action': OrderLogSchemaActionEnum;
    /**
     * 
     * @type {string}
     * @memberof OrderLogSchema
     */
    'actionAt': string;
    /**
     * 
     * @type {string}
     * @memberof OrderLogSchema
     */
    'note'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum OrderLogSchemaActionEnum {
    PendingToConfirmed = 'pending-to-confirmed',
    ConfirmedToPreparing = 'confirmed-to-preparing',
    PreparingToPrepared = 'preparing-to-prepared',
    PreparedToShipping = 'prepared-to-shipping',
    ShippingToCompleted = 'shipping-to-completed',
    CancelByCustomer = 'cancel-by-customer',
    FailedBySales = 'failed-by-sales',
    FailedByWarehouse = 'failed-by-warehouse',
    FailedBySystem = 'failed-by-system'
}


