/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentSchema
 */
export interface PaymentSchema {
    /**
     * 
     * @type {string}
     * @memberof PaymentSchema
     */
    'method': PaymentSchemaMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentSchema
     */
    'status': PaymentSchemaStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentSchema
     */
    'url'?: string;
    /**
     * additional data of payment
     * @type {object}
     * @memberof PaymentSchema
     */
    'paymentData'?: object;
}

/**
    * @export
    * @enum {string}
    */
export enum PaymentSchemaMethodEnum {
    Cod = 'COD',
    Vnpay = 'VNPAY',
    Vnbank = 'VNBANK',
    Intcard = 'INTCARD'
}
/**
    * @export
    * @enum {string}
    */
export enum PaymentSchemaStatusEnum {
    Pending = 'pending',
    Processing = 'processing',
    WaitForPayment = 'wait-for-payment',
    Completed = 'completed',
    Canceled = 'canceled',
    Failed = 'failed'
}


