/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CustomerSchema } from './customer-schema';
// May contain unused imports in some cases
// @ts-ignore
import { OrderLogSchema } from './order-log-schema';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentSchema } from './payment-schema';
// May contain unused imports in some cases
// @ts-ignore
import { ProductSchema } from './product-schema';
// May contain unused imports in some cases
// @ts-ignore
import { ShippingSchema } from './shipping-schema';

/**
 * 
 * @export
 * @interface PreviewOrderResponseDto
 */
export interface PreviewOrderResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PreviewOrderResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof PreviewOrderResponseDto
     */
    'updatedAt': string;
    /**
     * 
     * @type {CustomerSchema}
     * @memberof PreviewOrderResponseDto
     */
    'customer': CustomerSchema;
    /**
     * 
     * @type {Array<ProductSchema>}
     * @memberof PreviewOrderResponseDto
     */
    'products': Array<ProductSchema>;
    /**
     * 
     * @type {PaymentSchema}
     * @memberof PreviewOrderResponseDto
     */
    'payment': PaymentSchema;
    /**
     * 
     * @type {ShippingSchema}
     * @memberof PreviewOrderResponseDto
     */
    'shipping': ShippingSchema;
    /**
     * Order logs
     * @type {Array<OrderLogSchema>}
     * @memberof PreviewOrderResponseDto
     */
    'orderLogs': Array<OrderLogSchema>;
    /**
     * Total price of order
     * @type {number}
     * @memberof PreviewOrderResponseDto
     */
    'totalPrice': number;
}

