/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ImageSchema } from './image-schema';
// May contain unused imports in some cases
// @ts-ignore
import { PriceSchema } from './price-schema';

/**
 * 
 * @export
 * @interface ProductSchema
 */
export interface ProductSchema {
    /**
     * 
     * @type {string}
     * @memberof ProductSchema
     */
    'skuId': string;
    /**
     * 
     * @type {string}
     * @memberof ProductSchema
     */
    'productName': string;
    /**
     * 
     * @type {ImageSchema}
     * @memberof ProductSchema
     */
    'image': ImageSchema;
    /**
     * 
     * @type {PriceSchema}
     * @memberof ProductSchema
     */
    'unitPrice': PriceSchema;
    /**
     * 
     * @type {number}
     * @memberof ProductSchema
     */
    'quantity': number;
    /**
     * 
     * @type {string}
     * @memberof ProductSchema
     */
    'productType'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductSchema
     */
    'serialNumber'?: Array<string>;
}

