/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ImageSchema } from './image-schema';
// May contain unused imports in some cases
// @ts-ignore
import { PriceDto } from './price-dto';
// May contain unused imports in some cases
// @ts-ignore
import { Tag } from './tag';

/**
 * 
 * @export
 * @interface ProductInListDto
 */
export interface ProductInListDto {
    /**
     * id of product
     * @type {string}
     * @memberof ProductInListDto
     */
    'id': string;
    /**
     * id of sku
     * @type {string}
     * @memberof ProductInListDto
     */
    'skuId': string;
    /**
     * name of product
     * @type {string}
     * @memberof ProductInListDto
     */
    'name': string;
    /**
     * name of model
     * @type {string}
     * @memberof ProductInListDto
     */
    'modelName': string;
    /**
     * name of brand
     * @type {string}
     * @memberof ProductInListDto
     */
    'brandName': string;
    /**
     * 
     * @type {PriceDto}
     * @memberof ProductInListDto
     */
    'price': PriceDto;
    /**
     * 
     * @type {Array<ImageSchema>}
     * @memberof ProductInListDto
     */
    'images': Array<ImageSchema>;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof ProductInListDto
     */
    'tags'?: Array<Tag>;
}

