/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttributeInProductDto } from './attribute-in-product-dto';
// May contain unused imports in some cases
// @ts-ignore
import { Brand } from './brand';
// May contain unused imports in some cases
// @ts-ignore
import { ImageSchema } from './image-schema';
// May contain unused imports in some cases
// @ts-ignore
import { VariationDto } from './variation-dto';

/**
 * 
 * @export
 * @interface ProductDto
 */
export interface ProductDto {
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    'productId': string;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    'productName': string;
    /**
     * 
     * @type {Brand}
     * @memberof ProductDto
     */
    'brand': Brand;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    'description': string;
    /**
     * 
     * @type {Array<AttributeInProductDto>}
     * @memberof ProductDto
     */
    'attributes': Array<AttributeInProductDto>;
    /**
     * 
     * @type {Array<ImageSchema>}
     * @memberof ProductDto
     */
    'images': Array<ImageSchema>;
    /**
     * 
     * @type {Array<VariationDto>}
     * @memberof ProductDto
     */
    'variations': Array<VariationDto>;
}

