/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductCartSchema
 */
export interface ProductCartSchema {
    /**
     * Product ID
     * @type {string}
     * @memberof ProductCartSchema
     */
    'productId': string;
    /**
     * Sku ID
     * @type {string}
     * @memberof ProductCartSchema
     */
    'skuId': string;
    /**
     * Product quantity
     * @type {number}
     * @memberof ProductCartSchema
     */
    'quantity': number;
    /**
     * Product created at
     * @type {string}
     * @memberof ProductCartSchema
     */
    'createdAt'?: string;
    /**
     * Product updated at
     * @type {string}
     * @memberof ProductCartSchema
     */
    'updatedAt'?: string;
}

