/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SerialNumber
 */
export interface SerialNumber {
    /**
     * 
     * @type {string}
     * @memberof SerialNumber
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof SerialNumber
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof SerialNumber
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof SerialNumber
     */
    'number': string;
    /**
     * 
     * @type {string}
     * @memberof SerialNumber
     */
    'skuId': string;
    /**
     * 
     * @type {string}
     * @memberof SerialNumber
     */
    'status': SerialNumberStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SerialNumberStatusEnum {
    Available = 'available',
    Holding = 'holding',
    Sold = 'sold'
}


