/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderLogSchema } from './order-log-schema';

/**
 * 
 * @export
 * @interface ShippingSchema
 */
export interface ShippingSchema {
    /**
     * 
     * @type {string}
     * @memberof ShippingSchema
     */
    'orderShipCode': string;
    /**
     * 
     * @type {string}
     * @memberof ShippingSchema
     */
    'provider': ShippingSchemaProviderEnum;
    /**
     * 
     * @type {number}
     * @memberof ShippingSchema
     */
    'fee': number;
    /**
     * 
     * @type {string}
     * @memberof ShippingSchema
     */
    'expectedDeliveryTime': string;
    /**
     * 
     * @type {string}
     * @memberof ShippingSchema
     */
    'trackingLink': string;
    /**
     * 
     * @type {Array<OrderLogSchema>}
     * @memberof ShippingSchema
     */
    'logs'?: Array<OrderLogSchema>;
}

/**
    * @export
    * @enum {string}
    */
export enum ShippingSchemaProviderEnum {
    Giaohangnhanh = 'giaohangnhanh'
}


