/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttributeInProductSchema } from './attribute-in-product-schema';
// May contain unused imports in some cases
// @ts-ignore
import { ImageSchema } from './image-schema';
// May contain unused imports in some cases
// @ts-ignore
import { PriceSchema } from './price-schema';

/**
 * 
 * @export
 * @interface SKU
 */
export interface SKU {
    /**
     * 
     * @type {string}
     * @memberof SKU
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof SKU
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof SKU
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof SKU
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof SKU
     */
    'spuId': string;
    /**
     * 
     * @type {string}
     * @memberof SKU
     */
    'spuModelSlug': string;
    /**
     * 
     * @type {PriceSchema}
     * @memberof SKU
     */
    'price': PriceSchema;
    /**
     * 
     * @type {ImageSchema}
     * @memberof SKU
     */
    'image': ImageSchema;
    /**
     * 
     * @type {string}
     * @memberof SKU
     */
    'status': SKUStatusEnum;
    /**
     * 
     * @type {Array<AttributeInProductSchema>}
     * @memberof SKU
     */
    'attributes': Array<AttributeInProductSchema>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SKU
     */
    'tags': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SKU
     */
    'description'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SKUStatusEnum {
    Selling = 'selling',
    Deleted = 'deleted',
    NewlyReleased = 'newly-released'
}


