/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SortProductsDto
 */
export interface SortProductsDto {
    /**
     * 
     * @type {string}
     * @memberof SortProductsDto
     */
    'orderBy': string;
    /**
     * 
     * @type {string}
     * @memberof SortProductsDto
     */
    'order': SortProductsDtoOrderEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SortProductsDtoOrderEnum {
    Asc = 'asc',
    Desc = 'desc'
}


