/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SortSkuDto
 */
export interface SortSkuDto {
    /**
     * Key of Entity to sort
     * @type {string}
     * @memberof SortSkuDto
     */
    'orderBy': string;
    /**
     * Order of sorting
     * @type {string}
     * @memberof SortSkuDto
     */
    'order': SortSkuDtoOrderEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SortSkuDtoOrderEnum {
    Asc = 'asc',
    Desc = 'desc'
}


