/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttributeInProductSchema } from './attribute-in-product-schema';
// May contain unused imports in some cases
// @ts-ignore
import { SPUModelSchema } from './spumodel-schema';

/**
 * 
 * @export
 * @interface SPU
 */
export interface SPU {
    /**
     * 
     * @type {string}
     * @memberof SPU
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof SPU
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof SPU
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof SPU
     */
    'brandId': string;
    /**
     * 
     * @type {string}
     * @memberof SPU
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof SPU
     */
    'name': string;
    /**
     * 
     * @type {Array<AttributeInProductSchema>}
     * @memberof SPU
     */
    'commonAttributes': Array<AttributeInProductSchema>;
    /**
     * 
     * @type {Array<SPUModelSchema>}
     * @memberof SPU
     */
    'models': Array<SPUModelSchema>;
    /**
     * 
     * @type {string}
     * @memberof SPU
     */
    'status': SPUStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof SPU
     */
    'description'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SPUStatusEnum {
    Available = 'available',
    Deleted = 'deleted'
}


