/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttributeInProductSchemaDto } from './attribute-in-product-schema-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ImageSchemaDto } from './image-schema-dto';

/**
 * 
 * @export
 * @interface SPUModelSchemaDto
 */
export interface SPUModelSchemaDto {
    /**
     * 
     * @type {string}
     * @memberof SPUModelSchemaDto
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof SPUModelSchemaDto
     */
    'name': string;
    /**
     * 
     * @type {Array<ImageSchemaDto>}
     * @memberof SPUModelSchemaDto
     */
    'images': Array<ImageSchemaDto>;
    /**
     * Model attributes
     * @type {Array<AttributeInProductSchemaDto>}
     * @memberof SPUModelSchemaDto
     */
    'attributes': Array<AttributeInProductSchemaDto>;
    /**
     * 
     * @type {string}
     * @memberof SPUModelSchemaDto
     */
    'description'?: string;
}

