/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttributeInProductSchema } from './attribute-in-product-schema';
// May contain unused imports in some cases
// @ts-ignore
import { ImageSchema } from './image-schema';

/**
 * 
 * @export
 * @interface SPUModelSchema
 */
export interface SPUModelSchema {
    /**
     * 
     * @type {string}
     * @memberof SPUModelSchema
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof SPUModelSchema
     */
    'name': string;
    /**
     * 
     * @type {Array<AttributeInProductSchema>}
     * @memberof SPUModelSchema
     */
    'attributes': Array<AttributeInProductSchema>;
    /**
     * 
     * @type {Array<ImageSchema>}
     * @memberof SPUModelSchema
     */
    'images': Array<ImageSchema>;
    /**
     * 
     * @type {string}
     * @memberof SPUModelSchema
     */
    'description'?: string;
}

