/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateBrandDto
 */
export interface UpdateBrandDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateBrandDto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBrandDto
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBrandDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBrandDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBrandDto
     */
    'status'?: UpdateBrandDtoStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateBrandDtoStatusEnum {
    Active = 'active',
    Inactive = 'inactive',
    Deleted = 'deleted'
}


