/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UpdateSerialNumberDto } from './update-serial-number-dto';

/**
 * 
 * @export
 * @interface UpdateOrderStatusDto
 */
export interface UpdateOrderStatusDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateOrderStatusDto
     */
    'orderStatus': UpdateOrderStatusDtoOrderStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateOrderStatusDto
     */
    'note': string;
    /**
     * 
     * @type {Array<UpdateSerialNumberDto>}
     * @memberof UpdateOrderStatusDto
     */
    'updateSerialNumbers'?: Array<UpdateSerialNumberDto>;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateOrderStatusDtoOrderStatusEnum {
    Pending = 'pending',
    Confirmed = 'confirmed',
    Preparing = 'preparing',
    Prepared = 'prepared',
    Shipping = 'shipping',
    Canceled = 'canceled',
    Failed = 'failed',
    Completed = 'completed'
}


