/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BlockUserDto } from './block-user-dto';

/**
 * 
 * @export
 * @interface UpdateUserMntDto
 */
export interface UpdateUserMntDto {
    /**
     * User role to update
     * @type {string}
     * @memberof UpdateUserMntDto
     */
    'role'?: UpdateUserMntDtoRoleEnum;
    /**
     * 
     * @type {BlockUserDto}
     * @memberof UpdateUserMntDto
     */
    'block'?: BlockUserDto;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateUserMntDtoRoleEnum {
    Sales = 'sales',
    Warehouse = 'warehouse'
}


