/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateTagDto
 */
export interface UpdateTagDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTagDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTagDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTagDto
     */
    'status'?: UpdateTagDtoStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateTagDtoStatusEnum {
    Active = 'active',
    Deleted = 'deleted'
}


