/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateAttributeDto
 */
export interface UpdateAttributeDto {
    /**
     * Attribute name, can be translated
     * @type {string}
     * @memberof UpdateAttributeDto
     */
    'name'?: string;
    /**
     * Attribute unit
     * @type {string}
     * @memberof UpdateAttributeDto
     */
    'unit'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAttributeDto
     */
    'description'?: string;
    /**
     * Attribute status
     * @type {string}
     * @memberof UpdateAttributeDto
     */
    'status'?: UpdateAttributeDtoStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateAttributeDtoStatusEnum {
    Available = 'available',
    Deleted = 'deleted'
}


