/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AvatarSchema } from './avatar-schema';
// May contain unused imports in some cases
// @ts-ignore
import { UserAddressSchema } from './user-address-schema';
// May contain unused imports in some cases
// @ts-ignore
import { UserBlockSchema } from './user-block-schema';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'emailVerified': boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'provider': UserProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'role': UserRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'socialId'?: string;
    /**
     * 
     * @type {AvatarSchema}
     * @memberof User
     */
    'avatar'?: AvatarSchema;
    /**
     * 
     * @type {Array<UserAddressSchema>}
     * @memberof User
     */
    'address'?: Array<UserAddressSchema>;
    /**
     * 
     * @type {UserBlockSchema}
     * @memberof User
     */
    'block'?: UserBlockSchema;
}

/**
    * @export
    * @enum {string}
    */
export enum UserProviderEnum {
    Google = 'google',
    Facebook = 'facebook',
    Apple = 'apple',
    Email = 'email'
}
/**
    * @export
    * @enum {string}
    */
export enum UserRoleEnum {
    Manager = 'manager',
    Customer = 'customer',
    Sales = 'sales',
    Warehouse = 'warehouse'
}


