/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BlockActivityLog } from './block-activity-log';

/**
 * 
 * @export
 * @interface UserBlockSchema
 */
export interface UserBlockSchema {
    /**
     * 
     * @type {boolean}
     * @memberof UserBlockSchema
     */
    'isBlocked': boolean;
    /**
     * 
     * @type {Array<BlockActivityLog>}
     * @memberof UserBlockSchema
     */
    'activityLogs': Array<BlockActivityLog>;
}

