/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserDistrictResponseDto } from './user-district-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import { UserProvinceResponseDto } from './user-province-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import { UserWardResponseDto } from './user-ward-response-dto';

/**
 * 
 * @export
 * @interface UserAddressResponseDto
 */
export interface UserAddressResponseDto {
    /**
     * 
     * @type {UserProvinceResponseDto}
     * @memberof UserAddressResponseDto
     */
    'provinceLevel': UserProvinceResponseDto;
    /**
     * 
     * @type {UserDistrictResponseDto}
     * @memberof UserAddressResponseDto
     */
    'districtLevel': UserDistrictResponseDto;
    /**
     * 
     * @type {UserWardResponseDto}
     * @memberof UserAddressResponseDto
     */
    'wardLevel': UserWardResponseDto;
    /**
     * 
     * @type {string}
     * @memberof UserAddressResponseDto
     */
    'detail': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserAddressResponseDto
     */
    'isDefault': boolean;
    /**
     * 
     * @type {string}
     * @memberof UserAddressResponseDto
     */
    'customerName': string;
    /**
     * The phone number of customer
     * @type {string}
     * @memberof UserAddressResponseDto
     */
    'phoneNumbers': string;
    /**
     * 
     * @type {string}
     * @memberof UserAddressResponseDto
     */
    'type': string;
}

