/* tslint:disable */
/* eslint-disable */
/**
 * TechCell RESTful API Documentations
 * The documentations of the TechCell RESTful API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: teams@techcell.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AttributeInProductDto } from './attribute-in-product-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ImageSchema } from './image-schema';
// May contain unused imports in some cases
// @ts-ignore
import { PriceDto } from './price-dto';

/**
 * 
 * @export
 * @interface VariationDto
 */
export interface VariationDto {
    /**
     * 
     * @type {string}
     * @memberof VariationDto
     */
    'skuId': string;
    /**
     * 
     * @type {PriceDto}
     * @memberof VariationDto
     */
    'price': PriceDto;
    /**
     * 
     * @type {Array<AttributeInProductDto>}
     * @memberof VariationDto
     */
    'attributes': Array<AttributeInProductDto>;
    /**
     * 
     * @type {Array<string>}
     * @memberof VariationDto
     */
    'tags': Array<string>;
    /**
     * 
     * @type {ImageSchema}
     * @memberof VariationDto
     */
    'image'?: ImageSchema;
}

